### ISSUE TITLE
Releases should have a consistent order

### ISSUE THREAD

**Issue by Ravencentric** [ThaUnknown/releases-moe#10]
example below:

https://github.com/ThaUnknown/releases-moe/assets/78981416/3e28f37e-61e0-4357-bfe8-2fa29eacc49b

perhaps isbest dual > isbest single > alt dual > alt single? 

or maybe:
BEST:
release1 (dual) release2 (single)

ALT:
release1 (dual) release2 (single)

**Comment by ThaUnknown** [comment]
sorted by best > dual > group alphabetically
