### ISSUE TITLE
sort by available

### ISSUE THREAD

**Issue by Ravencentric** [ThaUnknown/releases-moe#11]
![image](https://github.com/ThaUnknown/releases-moe/assets/78981416/3f937240-cc91-488f-b3b5-19da2f69b56f)
the first results should be the available ones, not the empty ones

**Comment by ThaUnknown** [comment]
@Ravencentric this is fixed, BUT it's limited to the first page of 50 items, if there's an item on the 2nd page [so 51st result or higher], it won't show up on the start until you make a more accurate query
