### ISSUE TITLE
strip spaces at the start and end of notes

### ISSUE THREAD

**Issue by Ravencentric** [ThaUnknown/releases-moe#9]
![image](https://github.com/ThaUnknown/releases-moe/assets/78981416/3d9de49e-10a4-4c9e-bd7b-d387e87d2f6a)

**Comment by ThaUnknown** [comment]
just dont paste notes with a fuckload of spaces???????

**Comment by Ravencentric** [comment]
copying from sheet simply ends up with those spaces, not like im personally adding them
